-- ============================================================
-- KoraBiz Management System - Supabase Schema Bootstrap
-- Run this in your Supabase project's SQL Editor (supabase.com)
-- ============================================================

-- Helper function to check if current authenticated user is an admin
-- Using SECURITY DEFINER avoids infinite recursion on profiles table policies
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- ============================================================
-- 1. Profiles
-- ============================================================
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  email text,
  role text default 'user',
  plan_type text default 'standard',
  approved boolean default false,
  show_profit boolean default false,
  company_name text,
  company_location text,
  company_phone text,
  company_tin text,
  logo_url text,
  signature_url text,
  stamp_url text,
  created_at timestamp with time zone default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id);

drop policy if exists "Admins can view all profiles" on public.profiles;
create policy "Admins can view all profiles"
  on public.profiles for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can update all profiles" on public.profiles;
create policy "Admins can update all profiles"
  on public.profiles for update
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can delete profiles" on public.profiles;
create policy "Admins can delete profiles"
  on public.profiles for delete
  to authenticated
  using (public.is_admin());

-- ============================================================
-- 2. Subscriptions
-- ============================================================
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  plan_type text default 'standard',
  start_date date default now(),
  expiry_date date,
  is_lifetime boolean default false,
  payment_status text default 'pending',
  created_at timestamp with time zone default now()
);

alter table public.subscriptions enable row level security;

drop policy if exists "Users can view own subscription" on public.subscriptions;
create policy "Users can view own subscription"
  on public.subscriptions for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Admins can view all subscriptions" on public.subscriptions;
create policy "Admins can view all subscriptions"
  on public.subscriptions for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can update subscriptions" on public.subscriptions;
create policy "Admins can update subscriptions"
  on public.subscriptions for update
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can insert subscriptions" on public.subscriptions;
create policy "Admins can insert subscriptions"
  on public.subscriptions for insert
  to authenticated
  with check (public.is_admin());

drop policy if exists "Admins can delete subscriptions" on public.subscriptions;
create policy "Admins can delete subscriptions"
  on public.subscriptions for delete
  to authenticated
  using (public.is_admin());

-- ============================================================
-- 3. Payment Requests
-- ============================================================
create table if not exists public.payment_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  plan_type text not null,
  amount int not null,
  transaction_id text,
  sender_name text,
  status text default 'pending',
  created_at timestamp with time zone default now()
);

alter table public.payment_requests enable row level security;

drop policy if exists "Users can view own payment requests" on public.payment_requests;
create policy "Users can view own payment requests"
  on public.payment_requests for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can insert own payment requests" on public.payment_requests;
create policy "Users can insert own payment requests"
  on public.payment_requests for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Admins can view all payment requests" on public.payment_requests;
create policy "Admins can view all payment requests"
  on public.payment_requests for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can update payment requests" on public.payment_requests;
create policy "Admins can update payment requests"
  on public.payment_requests for update
  to authenticated
  using (public.is_admin());

-- ============================================================
-- 4. Products
-- ============================================================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  category text not null,
  quantity int not null default 0,
  buying_price int not null default 0,
  selling_price int not null default 0,
  low_stock_threshold int,
  created_at timestamp with time zone default now()
);

alter table public.products enable row level security;

drop policy if exists "Users can manage own products" on public.products;
create policy "Users can manage own products"
  on public.products for all
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Admins can view all products" on public.products;
create policy "Admins can view all products"
  on public.products for select
  to authenticated
  using (public.is_admin());

-- ============================================================
-- 5. Sales
-- ============================================================
create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  product_name text not null,
  quantity_sold int not null default 0,
  total int not null default 0,
  payment_method text default 'cash',
  payment_status text default 'paid',
  amount_paid int default 0,
  extra_fees int default 0,
  profit int,
  created_at timestamp with time zone default now()
);

alter table public.sales enable row level security;

drop policy if exists "Users can manage own sales" on public.sales;
create policy "Users can manage own sales"
  on public.sales for all
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Admins can view all sales" on public.sales;
create policy "Admins can view all sales"
  on public.sales for select
  to authenticated
  using (public.is_admin());

-- ============================================================
-- 6. Sale Items
-- ============================================================
create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  product_id bigint references public.products(id),
  product_name text not null,
  quantity_sold int not null default 0,
  selling_price int not null default 0,
  buying_price int default 0,
  total int not null default 0,
  is_consignment boolean default false,
  created_at timestamp with time zone default now()
);

alter table public.sale_items enable row level security;

drop policy if exists "Users can manage own sale items" on public.sale_items;
create policy "Users can manage own sale items"
  on public.sale_items for all
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Admins can view all sale items" on public.sale_items;
create policy "Admins can view all sale items"
  on public.sale_items for select
  to authenticated
  using (public.is_admin());

-- ============================================================
-- 7. Credits Given (Receivables from Customers)
-- ============================================================
create table if not exists public.credits_given (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  customer_name text not null,
  product_name text,
  quantity int default 0,
  amount int not null default 0,
  paid_amount int default 0,
  paid_at timestamp with time zone,
  paid_method text,
  date date default now(),
  notes text,
  status text default 'unpaid',
  sale_id bigint references public.sales(id),
  created_at timestamp with time zone default now()
);

alter table public.credits_given enable row level security;

drop policy if exists "Users can manage own credits given" on public.credits_given;
create policy "Users can manage own credits given"
  on public.credits_given for all
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Admins can view all credits given" on public.credits_given;
create policy "Admins can view all credits given"
  on public.credits_given for select
  to authenticated
  using (public.is_admin());

-- ============================================================
-- 8. Credits Taken (Payables to Suppliers)
-- ============================================================
create table if not exists public.credits_taken (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  supplier_name text not null,
  product_name text,
  quantity int default 0,
  amount int not null default 0,
  paid_amount int default 0,
  paid_at timestamp with time zone,
  paid_method text,
  date date default now(),
  notes text,
  status text default 'unpaid',
  created_at timestamp with time zone default now()
);

alter table public.credits_taken enable row level security;

drop policy if exists "Users can manage own credits taken" on public.credits_taken;
create policy "Users can manage own credits taken"
  on public.credits_taken for all
  to authenticated
  using (user_id = auth.uid());

-- ============================================================
-- 9. Expenses
-- ============================================================
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  description text not null,
  amount int not null default 0,
  created_at timestamp with time zone default now()
);

alter table public.expenses enable row level security;

drop policy if exists "Users can manage own expenses" on public.expenses;
create policy "Users can manage own expenses"
  on public.expenses for all
  to authenticated
  using (user_id = auth.uid());

-- ============================================================
-- 10. Devices
-- ============================================================
create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  device_id text not null,
  label text,
  last_seen timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

alter table public.devices enable row level security;

drop policy if exists "Users can manage own devices" on public.devices;
create policy "Users can manage own devices"
  on public.devices for all
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Admins can view all devices" on public.devices;
create policy "Admins can view all devices"
  on public.devices for select
  to authenticated
  using (public.is_admin());

-- ============================================================
-- 11. Activity Logs
-- ============================================================
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  user_email text,
  user_name text,
  action text not null,
  details text,
  ip_address text,
  device_id text,
  created_at timestamp with time zone default now()
);

alter table public.activity_logs enable row level security;

drop policy if exists "Users can insert own activity logs" on public.activity_logs;
create policy "Users can insert own activity logs"
  on public.activity_logs for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Users can view own activity logs" on public.activity_logs;
create policy "Users can view own activity logs"
  on public.activity_logs for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Admins can view all activity logs" on public.activity_logs;
create policy "Admins can view all activity logs"
  on public.activity_logs for select
  to authenticated
  using (public.is_admin());

-- ============================================================
-- 12. Quotations
-- ============================================================
create table if not exists public.quotations (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  customer_name text not null,
  date date default now(),
  items jsonb not null default '[]'::jsonb,
  total int not null default 0,
  status text default 'pending',
  sale_id bigint references public.sales(id),
  created_at timestamp with time zone default now()
);

alter table public.quotations enable row level security;

drop policy if exists "Users can manage own quotations" on public.quotations;
create policy "Users can manage own quotations"
  on public.quotations for all
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Admins can view all quotations" on public.quotations;
create policy "Admins can view all quotations"
  on public.quotations for select
  to authenticated
  using (public.is_admin());

-- ============================================================
-- 13. Auto-Create Profile Trigger on Auth Signup
-- ============================================================
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (
    id,
    full_name,
    email,
    role,
    plan_type,
    approved
  ) values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    new.email,
    'user',
    'standard',
    false
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- 14. Storage Buckets (Logos, Signatures, Stamps)
-- ============================================================
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public images access" on storage.objects;
create policy "Public images access"
  on storage.objects for select
  using (bucket_id = 'images');

drop policy if exists "Authenticated users can upload images" on storage.objects;
create policy "Authenticated users can upload images"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'images');

drop policy if exists "Users can update images" on storage.objects;
create policy "Users can update images"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'images');

drop policy if exists "Users can delete images" on storage.objects;
create policy "Users can delete images"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'images');

-- ============================================================
-- 15. PROMOTE YOUR ACCOUNT TO MASTER ADMIN
-- ============================================================
-- After you create an account on your app with your personal email,
-- run the query below in your Supabase SQL Editor (replace with your email):
--
-- UPDATE public.profiles
-- SET role = 'admin', approved = true
-- WHERE email = 'your-email@example.com';
-- ============================================================
